# This is a basic workflow to help you get started with Actions

name: autorun scripts

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *' # 06:00 UTC+8
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: install requirements
        run: pip install -r requirements.txt
      
      - name: run scripts
        run: python3 main.py
        env: 
          GITHUB_ACTIONS: true
          FL: ${{ secrets.FL }}
          BARK_URL: ${{ secrets.BARK_URL }}
          YS_COOKIE: ${{ secrets.YS_COOKIE }}


